#! /usr/bin/env node
/* vim: ft=javascript
 *
 * build.js
 * Copyright (C) 2013 Adrian Perez <aperez@igalia.com>
 *
 * Distributed under terms of the MIT license.
 */

var S = require("./site.js");
var P = require("path");
var F = require("fs");

var draft = (process.argv.length > 2) && (process.argv[2] == "draft");

site = new S.Site(".", draft);

for (var kind in site.content) {
  var items = site.content[kind];
  console.log("Building “" + kind + "”:");
  for (var i = 0; i < items.length; i++) {
    var item = items[i];
    var dest = item.url();
    console.log("  " + item.output_suffix() + ": " + item.relpath());
    F.writeFile(dest, item.render(), function (err) {
      if (err) throw err;
    });
  }
}

